plugins {
    id 'fabric-loom' version '1.16.3'
    id 'maven-publish'
}

version = project.version
group = project.group
base.archivesName = "SpinMyCrystals-1.21.11"

java {
    toolchain.languageVersion = JavaLanguageVersion.of(project.java_version)
    withSourcesJar()
}

sourceSets {
    main {
        java {
            srcDir '../../common/src/main/java'
        }
    }
}

repositories {
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/releases/"
    }
}

loom {
    runs {
        client {
            client()
            setConfigName('Fabric Client 1.21.11')
            ideConfigGenerated(true)
            runDir('run')
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    modCompileOnly "com.terraformersmc:modmenu:17.0.1-beta.1"
}

processResources {
    var expandProps = [
            'version': project.version,
            'mod_name': project.mod_name,
            'mod_author': project.mod_author,
            'mod_id': project.mod_id,
            'description': project.description,
            'license': project.license,
            'fabric_loader_version': project.fabric_loader_version,
            'minecraft_version': project.minecraft_version,
            'java_version': project.java_version
    ]
    inputs.properties(expandProps)
    filesMatching('fabric.mod.json') {
        expand(expandProps)
    }
    filesMatching('*.mixins.json') {
        expand(expandProps)
    }
}

tasks.withType(Jar).configureEach {
    from(rootProject.file('LICENSE')) {
        rename { "${it}_${project.mod_name}" }
    }
}

jar {
    manifest {
        attributes([
                'Specification-Title'   : project.mod_name,
                'Specification-Vendor'  : project.mod_author,
                'Specification-Version' : project.jar.archiveVersion,
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor' : project.mod_author,
                'Built-On-Minecraft'    : project.minecraft_version
        ])
    }
}
