version=1.0.0
group=dev.manere.spinmycrystals
java_version=21

minecraft_version=1.21.11
minecraft_version_min=1.21.11
minecraft_version_max=1.21.11
mod_name=SpinMyCrystals
mod_author=manereisbad
mod_id=spinmycrystals
license=MIT
credits=
description=Make my crystals spin! Built by manere with <3

fabric_version=0.141.6+1.21.11
fabric_loader_version=0.19.2
fabric.loom.disableObfuscation=false
