version=1.0.0
group=dev.manere.spinmycrystals
java_version=25

minecraft_version=26.2
minecraft_version_min=26.2
minecraft_version_max=26.2
mod_name=SpinMyCrystals
mod_author=manereisbad
mod_id=spinmycrystals
license=MIT
credits=
description=Make my crystals spin! Built by manere with <3

fabric_version=0.157.0+26.2
fabric_loader_version=0.19.2
